### ISSUE TITLE
Unable to dump iDRAC telemetry metrics

### ISSUE THREAD

**Issue by sakshiarora13** [nsfcac/MonSter#2]
**Description of issue**
While running midrac.py, encountered following error:
<img width="424" alt="image" src="https://user-images.githubusercontent.com/73195862/143009903-1230c492-b0fd-455a-a5d0-98c83696a2bc.png">

**Environment**
Operating System: CentOS-8.4
Python Version: 3.8.8
PostgreSQL Version: 13.5
Timescale DB Version:  2.5.0
iDRAC9 (Datacenter license), Firmware Version: 5.10.00.00

**Debugging output**
Added a debug statement in dump.py in function `dump_idrac()`:
`for metric in table_metrics:`
 &nbsp;&nbsp;&nbsp;&nbsp;`print(metrics)`

Attached is the screenshot of the output:
<img width="608" alt="image" src="https://user-images.githubusercontent.com/73195862/143010400-68347ebe-34a7-4d66-af6b-787dc31edff9.png">

The value coming from idrac for a metric is out of column data type range.

**Comment by Artlands** [comment]
Thanks for reporting this issue. 

This issue has been fixed by setting up the data type from "INT" to "BIGINT" in the metrics_definition table, which allows storing integers larger than 2147483648. All idrac tables are created based on this table.

Please pull the update and delete all idrac tables and metrics_definition table, then run `python tsdb.py` and `python midrac.py`.

Thanks!
